apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo "hello world" > /init/index.html
    volumeMounts:
    - name: shared-volume
      mountPath: /init
  containers:
  - name: main-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do sleep 1; done"]
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-volume
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
  volumes:
  - name: shared-volume
    emptyDir: {}
